#Generic Game Constants
UPDATE_RATE = 60 #Update GameState logic 60 times per second
WINDOW_WIDTH = 810
WINDOW_HEIGHT = 360


#Input Constants
MOUSE_EVENT_PRESS = 1
MOUSE_EVENT_RELEASE = 2
MOUSE_EVENT_DRAG = 3

MOUSE_GESTURE_STARTED = 1
MOUSE_GESTURE_COMPLETED = 2
MOUSE_GESTURE_ABORTED = 3


#Puzzle Constants
PUZZLE_BLOCK_SIDE_PIXEL_LENGTH = 90
PUZZLE_ELEMENT_SIDE_PIXEL_LENGTH = 30
PUZZLE_BLOCK_SIDE_TILE_LENGTH = (
        PUZZLE_BLOCK_SIDE_PIXEL_LENGTH/PUZZLE_ELEMENT_SIDE_PIXEL_LENGTH )

#platformer Constants
MAX_Y_VEL = 20
